server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lixiang?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zhangliang2012
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    host: 110.40.158.79
    port: 5672
    username: root
    password: zhangliang2012
    publisher-confirm-type: correlated

mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.lixiang.pojo    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
logging:
  level:
    com.lixiang.mapper: debug


# swagger 与  knife4j 界面

knife4j:
  enable: true
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License
    enableSwaggerModels: true
    swaggerModelName: 我的模型

# 阿里云短信配置
aliyun:
  message:
    accesskeyId: 12
    accessKeySecret: 12
    regionId: 14
    templateCode: 15


#    shiro配置
shiro:
  web:
    enabled: true
  loginUrl: /login